### ISSUE TITLE
async execute ()

### ISSUE THREAD

**Issue by naugustijr** [dimichgh/oja#11]
/Users/cetisoftware/Documents/app/oja-selling-example/src/services/item-details/action.js:7
    async execute() {
          ^^^^^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/cetisoftware/Documents/app/oja-selling-example/src/pages/item/index.js:5:27)

**Comment by austinkelleher** [comment]
The oja-selling-example uses Node 8+ features (including [async/await](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function)). If you use Node 8+, this error should go away.
